import type { Metadata } from "next";
import "./globals.css";
import { MockProvider } from "@/mockProvider";
import RecoilProvider from "@/recoilProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MockProvider>
          <RecoilProvider>{children}</RecoilProvider>
        </MockProvider>
      </body>
    </html>
  );
}
