import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Start the mocking when the app is running in development mode.
  if (typeof window === "undefined") {
    (async () => {
      const { server } = await import("../mocks/server");
      server.listen();
    })();
  } else {
    (async () => {
      const { worker } = await import("../mocks/browser");
      worker.start();
    })();
  }

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
